---
- name:  download boxfuse and install maven default-jdk
  hosts: maven
  become: yes

  tasks:
    - name: Clone of a single branch
      ansible.builtin.git:
        repo: git@github.com:boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/boxfuse-sample-java-war-hello
        single_branch: yes
        version: master

    - name: Ensure default-jdk package is present
      apt:
         name: default-jdk
         state: present

    - name: Ensure maven package is present
      apt:
         name: maven
         state: present

    - name: maven package
      command: mvn package /tmp/boxfuse-sample-java-war-hello/


- name: Install tomcat
  hosts: tomcat
  become: yes

  tasks:
    - name: Ensure tomcat is preset
      apt:
          name: tomcat9
          state: present

    - name: Ensure tomcat is preset
      service:
        name: tomcat
        state: started

    - name: Transfer file from ServerA to ServerB
      synchronize:
        src: /tmp/boxfuse-sample-java-war-hello/*.war
        dest: /opt/tomcat/webapps
      delegate_to: maven